openapi: '3.0.0'
info:
  title: FincasMs API's
  version: 1.0.0
servers:
  - url: http://localhost:8090/api
    description: Development server
  - url: https://localhost:8090/api
    description: Development server with TLS Profile
paths:
  /fincas/userFincas/{userId}:
    get:
      summary: List all fincas of a user
      operationId: getFincasByUserId
      tags:
        - fincas
      parameters:
        - name: userId
          in: path
          required: true
          description: The id of the user owner of the fincas
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fincas'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Finca:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        userLogin:
          type: string
      required:
        - id
        - nombre
        - userLogin
    Fincas:
      type: array
      items:
        $ref: '#/components/schemas/Finca'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
